### ISSUE TITLE
Unable to install erpnext using helm chart and azure mariadb database

### ISSUE THREAD

**Issue by SachinL9** [frappe/helm#102]
Hi

I am trying to setup erpnext using below steps referred from: https://helm.erpnext.com.
My k8s cluster is azure AKS. 
I have created a storage class named: rook-cephfs which is used in the helm deployment.
nginx ingress controller is also installed.

```
kubectl create namespace erpnextv904
kubectl apply -f mariadb-password.yaml -n erpnextv904

helm  upgrade --install frappe-bench-0001 --namespace erpnextv904 frappe/erpnext --version 3.2.31 \
 --set mariadbHost=mytestmariadbserver.mariadb.database.azure.com     \
 --set persistence.worker.storageClass=rook-cephfs    \
 --set persistence.logs.storageClass=rook-cephfs 

```

After this I have verified that in the azure storage account 2 file shares are created for pvc's frappe-bench-0001-erpnext and frappe-bench-0001-erpnext-logs.
These are file share contents of frappe-bench-0001-erpnext:
![image](https://user-images.githubusercontent.com/897328/139462658-3d2be81f-eda9-4cfc-8d72-3b693f83557d.png)

At this point the scheduler and worker containers are in State CrashLoopBackOff (due to healthcheck failure?). The logs dont show any errors.

Here are the default worker pod logs
```
Attempt 1 to connect to mytestmariadbserver.mariadb.database.azure.com:3306
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-queue:12000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-cache:13000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-socketio:11000
Connections OK
11:12:32 Worker rq:worker:9bc88174c71b4f1a9c21cd4f22f2e165.frappe-bench-0001-erpnext-worker-d-758ccb9f8-k77gc.10.default: started, version 1.8.1
11:12:32 Subscribing to channel rq:pubsub:9bc88174c71b4f1a9c21cd4f22f2e165.frappe-bench-0001-erpnext-worker-d-758ccb9f8-k77gc.10.default
11:12:32 *** Listening on default...
```

I would guess before installing the site the pods should be in stable/Running state. But I still tried to create site using steps here: https://helm.erpnext.com/kubernetes-resources/create-new-site-job

Here are the create site job logs:
```
kubectl logs create-new-site-erpnextv904--1-494j7  -n erpnextv904
Attempt 1 to connect to mytestmariadbserver.mariadb.database.azure.com:3306
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-queue:12000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-cache:13000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-socketio:11000
Connections OK
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 118, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 70, in main
    db_port=db_port,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 74, in _new_site
    no_mariadb_socket=no_mariadb_socket,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 108, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 16, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(force, source_sql, verbose, no_mariadb_socket=no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 39, in setup_database
    if force or (db_name not in dbman.get_database_list()):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 60, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 74, in connect
    self._conn = self.get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 82, in get_connection
    local_infile=frappe.conf.local_infile
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 921, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1018, in _process_auth
    pkt = self._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'mariadbadminuser'@'10.244.4.19' (using password: YES)")
```

From the default worker pod I verified that connection to the mysql database is successful. 
The root user seems to have access from all IPs:

SELECT user,authentication_string,plugin,host,`Grant_priv`  FROM mysql.user;
+-----------------+-----------------------+-----------------------+---------------------------------------------+------------+
| user            | authentication_string | plugin                | host                                        | Grant_priv |
+-----------------+-----------------------+-----------------------+---------------------------------------------+------------+
| mariadbadminuser      |                       |                       | %                                           | Y          |

I can see the site folder created in the file share. Here are its contents:
![image](https://user-images.githubusercontent.com/897328/139461464-fa597758-b7f0-4044-919c-16fa258771fa.png)

What am I missing? Any help greatly appreciated.

Thanks.
Sachin

**Comment by revant** [comment]
I've not used Azure's MariaDB.

can you check the contents of `common_site_config.json`. It should have the correct db and redis host(s)

The healthcheck for workers are trying to ping the db host:port using [wait-for-it](https://packages.debian.org/bullseye/wait-for-it)

**Comment by SachinL9** [comment]
Here are contents of common_site_config.json:

```
{
    "db_host": "mytestmariadbserver.mariadb.database.azure.com",
    "db_port": 3306,
    "redis_cache": "redis://frappe-bench-0001-erpnext-redis-cache:13000",
    "redis_queue": "redis://frappe-bench-0001-erpnext-redis-queue:12000",
    "redis_socketio": "redis://frappe-bench-0001-erpnext-redis-socketio:11000",
    "socketio_port": 9000
}
```

healthcheck.sh output - ran from within worker container:

```
Check mytestmariadbserver.mariadb.database.azure.com:3306
wait-for-it: waiting 1 seconds for mytestmariadbserver.mariadb.database.azure.com:3306
wait-for-it: mytestmariadbserver.mariadb.database.azure.com:3306 is available after 0 seconds
Check frappe-bench-0001-erpnext-redis-cache:13000
wait-for-it: waiting 1 seconds for frappe-bench-0001-erpnext-redis-cache:13000
wait-for-it: frappe-bench-0001-erpnext-redis-cache:13000 is available after 0 seconds
Check frappe-bench-0001-erpnext-redis-queue:12000
wait-for-it: waiting 1 seconds for frappe-bench-0001-erpnext-redis-queue:12000
wait-for-it: frappe-bench-0001-erpnext-redis-queue:12000 is available after 0 seconds
Check frappe-bench-0001-erpnext-redis-socketio:11000
wait-for-it: waiting 1 seconds for frappe-bench-0001-erpnext-redis-socketio:11000
wait-for-it: frappe-bench-0001-erpnext-redis-socketio:11000 is available after 0 seconds
```

**Comment by revant** [comment]
I guess you need to tweak configuration on Azure.

There is a wiki for AWS RDS config https://github.com/frappe/frappe/wiki/Using-Frappe-with-Amazon-RDS-(or-any-other-DBaaS)

Change similar settings on Azure. Do add a another wiki article for Azure. 

Check this for mariadb custom config https://github.com/frappe/bench/wiki/MariaDB-conf-for-Frappe
