### ISSUE TITLE
bench migrate failing on kubernetes

### ISSUE THREAD

**Issue by varunblaze** [frappe/helm#137]
## Description of the issue

  When the ERPNext  is deployed on kubernetes, bench migrate command fails. This is primary because k8s redis services doesn't have a port numbers and specifying a DNS name is enough. But the code is trying to split the config based on ":" 

common-site-config.json:

`
{
 "db_host": "common-services-mariadb.common-services.svc.cluster.local",
 "db_port": 3306,
 "redis_cache": "redis://common-services-redis-cache-master.common-services.svc.cluster.local",
 "redis_queue": "redis://common-services-redis-queue-master.common-services.svc.cluster.local",
 "redis_socketio": "redis://common-services-redis-socketio-master.common-services.svc.cluster.local",
 "socketio_port": 9000
}`

## Steps to reproduce the issue

1. Deploy Redis and mysql on k8s in different namespace
2. Deploy ERPNext /Frappe on k8s in a different namespace using the Helm Chart (helm.erpnext.com) by specifying redis urls.
2. Create site, install an app and run bench migrate (by SSHing into Scheduler pod)

### Observed result

  migrate fails with the below error:

`**check_redis
    redis_host, redis_port = redis_url.split(":")
ValueError: not enough values to unpack (expected 2, got 1)**
`
### Expected result

 Migrate should complete successfully.
### Stacktrace / full error message

$ bench --site xxxx migrate
Migrating xxxxxx

Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 407, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 40, in migrate
    service_status = check_connection(redis_services=["redis_cache"])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/connections.py", line 45, in check_connection
    service_status.update(check_redis(redis_services))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/connections.py", line 37, in **check_redis
    redis_host, redis_port = redis_url.split(":")
ValueError: not enough values to unpack (expected 2, got 1)**
```
```

## Additional information

OS version / distribution, `Frappe` install method, etc.

**Comment by revant** [comment]
for redis_cache, redis_queue, redis_socketio the uri pattern is `redis://<host>:<port>`, e.g. `redis://common-services-redis-cache-master.common-services.svc.cluster.local:6379`
