### ISSUE TITLE
Install on the OpenShift Platform

### ISSUE THREAD

**Issue by fgarcia78** [frappe/helm#161]
I'm trying to install this Helm Chart on OpenShift v4.9. Because OCP uses a different security approach I changed the following parameters (through custom `values.yaml` file) like this:

```
podSecurityContext:
  supplementalGroups: [1000730000]
securityContext:
  capabilities:
  runAsUser: 1000730000
```

I also changed `storageClass` setting to match my environment (IBM Cloud).

With those parameters I could install the Chart, but the pods keep crash-looping, with the exception of gunicorn pod which started correctly. The logs that I get from the faulty pods are the following:

Pod name: `frappe-bench-erpnext-nginx-75b9c86c56-d8qtk`:
```
PROXY_READ_TIMEOUT defaulting to 120
CLIENT_MAX_BODY_SIZE defaulting to 50m
/usr/local/bin/nginx-entrypoint.sh: line 49: /etc/nginx/conf.d/frappe.conf: Permission denied
2023/03/06 18:02:24 [emerg] 8#8: open() "/run/nginx.pid" failed (13: Permission denied)
nginx: [emerg] open() "/run/nginx.pid" failed (13: Permission denied)
```

Pod name: `frappe-bench-erpnext-scheduler-766859c998-9f5l2`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1386, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1552, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1580, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
```

Pod name: `frappe-bench-erpnext-socketio-c8fc48df-qdflz`:
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:12311
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:342:14)
    at Socket.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:223:14)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 12311
}
```

Pod name `frappe-bench-erpnext-worker-d-69cbbd8599-89k7z` (the other two worker pods show similar output):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1386, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1552, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1580, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
```

I know this project is intended for Kubernetes, but I think that it should be possible to install this platform on OCP, and that's what I want to achieve. I hope somebody could give me some pointers to make this work.

Thanks.

**Comment by revant** [comment]
- images have non root user called frappe with uid:gid 1000:1000
- any files owned by 1000:1000 are accessible in container
- storage class needs to be RWX. By default all providers have non RWX storage class set as default.

if I can get access to openshift setup, I can try few things.
