### ISSUE TITLE
CreateSite job sometimes has app installation error for custom image

### ISSUE THREAD

**Issue by codezart** [frappe/helm#177]
## Description of the issue
I have the `not enough values to unpack` error for a custom app installation inside k8s's create site job. Do you have any ideas why this error shows?

### Observed result
Sometimes an app encounters the error shown below.

### Expected result
custom app being installed correctly without errors
### Stacktrace / full error message if available

```

Installing custom_app...
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 218, in fetch_details_from_tag
    org, repo = org_repo
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 77, in new_site
    _new_site(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 106, in _new_site
    install_app(app, verbose=verbose, set_as_patched=not source_sql, force=False)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 268, in install_app
    required_app = parse_app_name(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 248, in parse_app_name
    _, repo, _ = fetch_details_from_tag(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 220, in fetch_details_from_tag
    org, repo = find_org(org_repo[0])
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 194, in find_org
    raise InvalidRemoteException
frappe.exceptions.InvalidRemoteException
```

**Comment by revant** [comment]
If this is custom image make sure you delete .git directory from apps.
